# Generated by Django 2.2.1 on 2019-05-12 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('start_time', 'end_time')},
        ),
    ]
