# Generated by Django 2.2.1 on 2019-05-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0002_auto_20190512_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagereport',
            name='severity_level',
            field=models.IntegerField(choices=[(0, 'Not Relevant'), (1, 'Minor'), (2, 'Medium'), (3, 'Heavy'), (4, 'Severe'), (5, 'Critical')], db_index=True),
        ),
        migrations.AlterField(
            model_name='videoreport',
            name='severity_level',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Relevant'), (1, 'Minor'), (2, 'Medium'), (3, 'Heavy'), (4, 'Severe'), (5, 'Critical')], db_index=True, null=True),
        ),
    ]
