# Generated by Django 2.2.1 on 2019-05-12 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0003_auto_20190512_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagereport',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='road.ReportCategory'),
        ),
    ]
