# Generated by Django 2.2.1 on 2019-05-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0005_auto_20190512_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoreport',
            name='reporter_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videoreport',
            name='title',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
